import {
  BarChart3,
  BookOpenCheck,
  CalendarDays,
  Calculator,
  ClipboardList,
  FileText,
  GraduationCap,
  Percent,
  PiggyBank,
  Target,
  Trophy,
} from "lucide-react";

export const tools = [
  {
    title: "Attendance Calculator",
    slug: "attendance-calculator",
    description:
      "Calculate attendance percentage, 75% attendance status, safe bunk count, and required classes.",
    category: "Students",
    icon: Calculator,
    status: "Live",
  },
  {
    title: "Marks Percentage Calculator",
    slug: "marks-percentage-calculator",
    description: "Calculate marks percentage from scored marks, total marks, grade range, and target marks.",
    category: "Students",
    icon: Percent,
    status: "Live",
  },
  {
    title: "GPA Calculator",
    slug: "gpa-calculator",
    description: "Calculate GPA, CGPA, credits, weighted grade points, and target GPA on 4.0 or 10.0 scales.",
    category: "Students",
    icon: GraduationCap,
    status: "Live",
  },
  {
    title: "Grade Calculator",
    slug: "grade-calculator",
    description: "Calculate weighted grade, assignment contribution, current grade, and target average.",
    category: "Students",
    icon: BarChart3,
    status: "Live",
  },
  {
    title: "Final Exam Calculator",
    slug: "final-exam-calculator",
    description: "Calculate what score you need on the final exam to reach your target course grade.",
    category: "Students",
    icon: Trophy,
    status: "Live",
  },
  {
    title: "Study Timetable Generator",
    slug: "study-timetable-generator",
    description: "Generate a study timetable from subjects, exam days, revision time, and study windows.",
    category: "Students",
    icon: CalendarDays,
    status: "Live",
  },
  {
    title: "Scholarship Eligibility Calculator",
    slug: "scholarship-eligibility-calculator",
    description: "Check scholarship eligibility using marks, family income, category, course level, and study type.",
    category: "Students",
    icon: PiggyBank,
    status: "Live",
  },
  {
    title: "Study Hours Calculator",
    slug: "study-hours-calculator",
    description: "Calculate daily study hours from exam days, subjects, syllabus load, revision time, and confidence.",
    category: "Students",
    icon: BookOpenCheck,
    status: "Live",
  },
  {
    title: "Assignment Deadline Planner",
    slug: "assignment-deadline-planner",
    description: "Plan assignment work by deadline, pages, tasks, daily available time, and review buffer.",
    category: "Students",
    icon: ClipboardList,
    status: "Live",
  },
  {
    title: "Exam Score Goal Planner",
    slug: "exam-score-goal-planner",
    description: "Set subject-wise score targets and calculate the marks needed to reach your overall exam goal.",
    category: "Students",
    icon: Target,
    status: "Live",
  },
  {
    title: "CGPA to Percentage Converter",
    slug: "cgpa-percentage-converter",
    description: "Convert CGPA to percentage and percentage to CGPA using common 10-point and 4-point formulas.",
    category: "Students",
    icon: GraduationCap,
    status: "Live",
  },
  {
    title: "Class 10/12 Board Percentage Calculator",
    slug: "board-percentage-calculator",
    description: "Calculate board exam percentage, best of five score, subject totals, and grade range.",
    category: "Students",
    icon: Percent,
    status: "Live",
  },
  {
    title: "Certificate Generator",
    slug: "certificate-generator",
    description: "Create printable course completion certificates with academy branding.",
    category: "Academies",
    icon: FileText,
    status: "Planned",
  },
];
