import {
  BarChart3,
  BookOpenCheck,
  CalendarDays,
  Calculator,
  Archive,
  ClipboardList,
  FileText,
  FileUser,
  FileCheck2,
  FileQuestion,
  FileSearch,
  GraduationCap,
  LayoutTemplate,
  ListChecks,
  Percent,
  PiggyBank,
  ReceiptText,
  Target,
  Trophy,
  TrendingUp,
  UserPlus,
  UsersRound,
  type LucideIcon,
} from "lucide-react";

export type ToolCategory = "Students" | "Teachers" | "Academies";

export type ToolItem = {
  title: string;
  slug: string;
  description: string;
  category: ToolCategory;
  icon: LucideIcon;
  status: "Live" | "Coming soon";
  isAi?: boolean;
};

export const tools: ToolItem[] = [
  {
    title: "AI Final Year Project Kit Generator",
    slug: "final-year-project-kit-generator",
    description: "Generate final year project ideas, architecture, documentation, viva questions, resume bullets, and starter ZIP.",
    category: "Students",
    isAi: true,
    icon: Archive,
    status: "Live",
  },
  {
    title: "AI Resume ATS Checker",
    slug: "resume-ats-checker",
    description: "Free ATS resume checker with AI resume roast, rejection reasons, keyword gaps, PDF report, and career roadmap.",
    category: "Students",
    isAi: true,
    icon: FileSearch,
    status: "Live",
  },
  {
    title: "AI Resume Builder",
    slug: "ai-resume-builder",
    description: "Build a clean ATS-friendly resume with AI templates, role keywords, smart bullets, preview, print, and download.",
    category: "Students",
    isAi: true,
    icon: FileUser,
    status: "Live",
  },
  {
    title: "Free Resume Builder",
    slug: "resume-builder-studio",
    description: "Free online AI resume maker with ATS-friendly templates, student and fresher formats, photo resume layouts, live editing, and PDF-ready export.",
    category: "Students",
    isAi: true,
    icon: LayoutTemplate,
    status: "Live",
  },
  {
    title: "Attendance Calculator",
    slug: "attendance-calculator",
    description:
      "Calculate attendance percentage, 75% attendance status, safe bunk count, and required classes.",
    category: "Students",
    icon: Calculator,
    status: "Live",
  },
  {
    title: "Marks Percentage Calculator",
    slug: "marks-percentage-calculator",
    description: "Calculate marks percentage from scored marks, total marks, grade range, and target marks.",
    category: "Students",
    icon: Percent,
    status: "Live",
  },
  {
    title: "GPA Calculator",
    slug: "gpa-calculator",
    description: "Calculate GPA, CGPA, credits, weighted grade points, and target GPA on 4.0 or 10.0 scales.",
    category: "Students",
    icon: GraduationCap,
    status: "Live",
  },
  {
    title: "Grade Calculator",
    slug: "grade-calculator",
    description: "Calculate weighted grade, assignment contribution, current grade, and target average.",
    category: "Students",
    icon: BarChart3,
    status: "Live",
  },
  {
    title: "Final Exam Calculator",
    slug: "final-exam-calculator",
    description: "Calculate what score you need on the final exam to reach your target course grade.",
    category: "Students",
    icon: Trophy,
    status: "Live",
  },
  {
    title: "Study Timetable Generator",
    slug: "study-timetable-generator",
    description: "Generate a study timetable from subjects, exam days, revision time, and study windows.",
    category: "Students",
    icon: CalendarDays,
    status: "Live",
  },
  {
    title: "Scholarship Eligibility Calculator",
    slug: "scholarship-eligibility-calculator",
    description: "Check scholarship eligibility using marks, family income, category, course level, and study type.",
    category: "Students",
    icon: PiggyBank,
    status: "Live",
  },
  {
    title: "Study Hours Calculator",
    slug: "study-hours-calculator",
    description: "Calculate daily study hours from exam days, subjects, syllabus load, revision time, and confidence.",
    category: "Students",
    icon: BookOpenCheck,
    status: "Live",
  },
  {
    title: "Assignment Deadline Planner",
    slug: "assignment-deadline-planner",
    description: "Plan assignment work by deadline, pages, tasks, daily available time, and review buffer.",
    category: "Students",
    icon: ClipboardList,
    status: "Live",
  },
  {
    title: "Exam Score Goal Planner",
    slug: "exam-score-goal-planner",
    description: "Set subject-wise score targets and calculate the marks needed to reach your overall exam goal.",
    category: "Students",
    icon: Target,
    status: "Live",
  },
  {
    title: "CGPA to Percentage Converter",
    slug: "cgpa-percentage-converter",
    description: "Convert CGPA to percentage and percentage to CGPA using common 10-point and 4-point formulas.",
    category: "Students",
    icon: GraduationCap,
    status: "Live",
  },
  {
    title: "Class 10/12 Board Percentage Calculator",
    slug: "board-percentage-calculator",
    description: "Calculate board exam percentage, best of five score, subject totals, and grade range.",
    category: "Students",
    icon: Percent,
    status: "Live",
  },
  {
    title: "AI Worksheet Generator",
    slug: "worksheet-generator",
    description: "Generate AI worksheets with sections, practice questions, marks, difficulty, and answer key.",
    category: "Teachers",
    isAi: true,
    icon: ClipboardList,
    status: "Live",
  },
  {
    title: "AI Report Card Generator",
    slug: "report-card-generator",
    description: "Generate AI report card remarks, parent comments, strengths, improvement plans, and next steps.",
    category: "Teachers",
    isAi: true,
    icon: FileCheck2,
    status: "Live",
  },
  {
    title: "AI Assignment Generator",
    slug: "assignment-generator",
    description: "Generate AI assignments with tasks, marks, learning goals, submission checklist, and rubric.",
    category: "Teachers",
    isAi: true,
    icon: ClipboardList,
    status: "Live",
  },
  {
    title: "AI Lesson Plan Generator",
    slug: "lesson-plan-generator",
    description: "Generate AI lesson plans with objectives, activities, assessment, homework, and closure.",
    category: "Teachers",
    isAi: true,
    icon: BookOpenCheck,
    status: "Live",
  },
  {
    title: "AI Quiz Generator",
    slug: "quiz-generator",
    description: "Generate AI quizzes with MCQs, true or false, short answers, answer keys, and explanations.",
    category: "Teachers",
    isAi: true,
    icon: ListChecks,
    status: "Live",
  },
  {
    title: "AI Question Paper Generator",
    slug: "question-paper-generator",
    description: "Generate AI question papers with class, subject, syllabus coverage, marks, difficulty, and answer key hints.",
    category: "Teachers",
    isAi: true,
    icon: FileQuestion,
    status: "Live",
  },
  {
    title: "Course Pricing Calculator",
    slug: "course-pricing-calculator",
    description: "Calculate profitable online course fees, revenue, net profit, margin, and break-even students.",
    category: "Academies",
    isAi: true,
    icon: TrendingUp,
    status: "Live",
  },
  {
    title: "Academy Profit Calculator",
    slug: "profit-calculator",
    description: "Calculate monthly academy revenue, expenses, net profit, margin, and AI profit strategy.",
    category: "Academies",
    isAi: true,
    icon: BarChart3,
    status: "Live",
  },
  {
    title: "Fee Receipt Generator",
    slug: "fee-receipt-generator",
    description: "Create printable student fee receipts with payment mode, due balance, copy, print, and download.",
    category: "Academies",
    icon: ReceiptText,
    status: "Live",
  },
  {
    title: "Admission Form Generator",
    slug: "admission-form-generator",
    description: "Create printable student admission forms with custom fields, documents, fees, print, and download.",
    category: "Academies",
    icon: UserPlus,
    status: "Live",
  },
  {
    title: "Batch Capacity Calculator",
    slug: "batch-capacity-calculator",
    description: "Calculate academy seats, batch capacity, occupancy, teacher load, and revenue potential.",
    category: "Academies",
    icon: UsersRound,
    status: "Live",
  },
  {
    title: "Certificate Generator",
    slug: "certificate-generator",
    description: "Create printable course completion, participation, achievement, workshop, and training certificates.",
    category: "Academies",
    icon: FileText,
    status: "Live",
  },
];
